server:
  port: 8000
spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        hbm2ddl:
          auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring_quartz
    username: postgres
    password: postgres
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          scheduler:
            instanceName: QuartzScheduler
            instanceId: AUTO
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 3
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            dataSource: quartzDs
          dataSource:
            quartzDs:
              driver: org.postgresql.Driver
              URL: jdbc:postgresql://localhost:5432/spring_quartz
              user: postgres
              password: postgres
              provider: hikaricp