server:
  port: 8000
spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        hbm2ddl:
          auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring_quartz
    username: postgres
    password: postgres
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always